spec/lob/v1/bank_account_spec.rb
spec/lob/v1/check_spec.rb
spec/lob/v1/job_spec.rb
spec/lob/v1/object_spec.rb
spec/lob_spec.rb

This should fix the issues seen in the broken tests.

fixes broken version tests

---

spec/lob/v1/job_spec.rb

Had to modify tests due to changes to multi-object support in the API.

fix(jobs): fixes multi-object job tests

---

.travis.yml
Gemfile
lob.gemspec

That. The JRuby failure is a little annoying, but should be fixed when 9000 is released in the next couple of months.

Don't fix prawn version unless you're using Ruby 1.9

---

lib/lob/v1/bank_account.rb
spec/lob/v1/bank_account_spec.rb
spec/lob/v1/check_spec.rb

@lob/api-engineering-team 
@pon how can I get the tests to pass for this?

adds bank account verify endpoint

---

examples/letters.rb
lib/lob/v1/letter.rb
lib/lob/v1/resource.rb
spec/lob/v1/letter_spec.rb
spec/samples/8.5x11.pdf

adds support for letters

---

.gitignore
Rakefile
lib/lob.rb
lob.gemspec
spec/lob/v1/area_spec.rb
spec/lob/v1/bank_account_spec.rb
spec/lob/v1/check_spec.rb
spec/lob/v1/country_spec.rb
spec/lob/v1/job_spec.rb
spec/lob/v1/letter_spec.rb
spec/lob/v1/object_spec.rb
spec/lob/v1/postcard_spec.rb
spec/lob/v1/route_spec.rb
spec/lob/v1/state_spec.rb
spec/samples/8.5x11.pdf

Should pass once the new version is ready.
@pon @elnaz @robinjoseph08

adds support for version 2015-04-11

---

lob.gemspec

updated gems

---

examples/letters.rb

@ami @leore @pon @elnaz @robinjoseph08 
:mans_shoe:

updated letters example

---

examples/postcards.rb

@robinjoseph08 @pon @ami @leore

updated postcard example

---

examples/checks.rb
examples/create_pdf.rb
examples/jobs.rb

fixes examples to work with the latest version

fixes examples to work with the new version

---

README.md
examples/README.md
examples/csv_postcards/create_postcards.rb
examples/csv_postcards/input.csv
examples/csv_postcards/postcard_back.html
examples/csv_postcards/postcard_front.html
spec/lob/v1/check_spec.rb
spec/lob/v1/letter_spec.rb

@pon @elnaz @leore @robinjoseph08 @russelltaylor05

added CSV and data example

---

lib/lob.rb
lob.gemspec

@pon @leore @elnaz @robinjoseph08

fix nested query parameters

---

examples/README.md
examples/verify/input.txt
examples/verify/verify.rb

@russelltaylor05 Look it over and run it, let me know if I need to make any changes.

added verify example

---

lib/lob.rb
lib/lob/v1/resource.rb
spec/lob/v1/postcard_spec.rb
spec/lob_spec.rb

Finally bring coverage up to 100%.
Closes #96 
@elnaz @mgartner

fix coverage

---

.travis.yml
examples/csv_postcards/create_postcards.rb

In preparation for 2015-12-22.

use size in postcard example instead of setting

---

lib/lob/v1/route.rb
spec/lob/v1/route_spec.rb

Adds a function to routes for hitting `GET /v1/routes/{id}`.

Adds find to routes

---

examples/checks.rb
examples/csv_postcards/create_postcards.rb
examples/jobs.rb
examples/letters.rb
examples/postcards.rb
examples/verify/verify.rb
spec/lob/v1/bank_account_spec.rb
spec/lob/v1/check_spec.rb

- Updates the examples to use the specific Lob Ruby test key. 
- Updates the check example and tests to work with the new API version.
- Refactors the bank account and check tests to make it easier to change the default bank account parameters.

Support API version 2016-03-21

---

README.md
lib/lob.rb
lib/lob/errors/lob_error.rb
spec/lob_spec.rb

Fixes #137 
Adds access to response headers by defining a singleton instance method on the response hash.

adds access to response headers

---

lob.gemspec

For https://github.com/lob/lob-ruby/issues/144

Pin rest-client to be >= 1.8 and < 3.0

---

README.md
lib/lob/client.rb
lib/lob/resources/address.rb
lib/lob/resources/intl_verifications.rb
lib/lob/resources/us_verifications.rb
spec/lob/resources/address_spec.rb
spec/lob/resources/intl_verifications_spec.rb
spec/lob/resources/us_verifications_spec.rb

feat(address-verification): Add USVerifications and IntlVerifications

---

README.md
examples/README.md
examples/csv_letters/create_letters.rb
examples/csv_postcards/create_postcards.rb
examples/letters.rb
examples/postcards.rb

What: update examples to use merge_variables
Why: new HTML feature new version

[WIP] chore(examples): update to use merge_variables

---

README.md
lib/lob/client.rb
lib/lob/resources/us_zip_lookups.rb
spec/lob/resources/us_zip_lookups_spec.rb

**what**
- add US Zip Lookups API endpoint to wrapper

feat(us-zip-lookups): add US Zip Lookups API endpoint to wrapper

---

lib/lob/resources/resource_base.rb
spec/lob/resources/postcard_spec.rb
spec/lob/resources/resource_base_spec.rb

WHAT: adds capability to pass in idempotency headers
WHY: because I need to finish my intern project

feat(idempotent-headers): adds capability to pass in idempotency headers

---

.travis.yml
spec/lob/resources/address_spec.rb

fix tests for address verification case handling

fix(tests): update tests

---

spec/lob/resources/intl_verifications_spec.rb

test(intl): Change intl_verifications test

---

spec/lob/resources/us_verifications_spec.rb

fix(test): Fix test to pass build

---

spec/lob/resources/letter_spec.rb

I think its a duplicate of the block on lines 58-73? Used https://www.diffchecker.com to confirm.

test(letters): remove duplicate test

---

spec/lob/resources/us_verifications_spec.rb

Accidentally left this copy pasta from the previous PR.

fix(test): Fix test name

---

.travis.yml
examples/README.md
examples/checks.rb
examples/csv_checks/create_checks.rb
examples/csv_letters/create_letters.rb
examples/csv_postcards/create_postcards.rb
examples/letters.rb
examples/postcards_template.rb
examples/self_mailers.rb
lib/lob/resources/resource_base.rb
lob.gemspec

Fixes some typos in the README. I ran every example and they all work fine, so... I think we're alright?

updated to 3.0.0

---

examples/README.md

This is a redo of https://github.com/lob/lob-ruby/pull/184. The branch the changes were made on were pruned.

added links to example scripts in README file

---

lib/lob/version.rb

This commit is only to update the version number

updated version number

---

lib/lob/resources/resource_base.rb

I need to be able to configure a proxy for rest-client on a per-client basis so I refactored this first to normalize between different request methods.

Refactor ResourceBase to make the options sent to rest-client more configurable

---

.github/workflows/run_tests_job.yml
.github/workflows/update_gem.yml

Removed the matrix variable from the update_gem action and expanded the pull_request action on run_tests_job action.

small fixes to github actions

---

CHANGELOG.md
lib/lob/version.rb

Added a pass through proxy to rest-client if supplied from @drcapulet

v5.4.5 release

---

lib/openapi_client/version.rb

updating the version number for https://github.com/lob/lob-ruby/pull/218

updated gem version

---

lib/openapi_client/models/bank_account.rb
lib/openapi_client/models/check.rb
lib/openapi_client/models/letter.rb
lib/openapi_client/models/postcard.rb
lib/openapi_client/models/self_mailer.rb
lib/openapi_client/models/thumbnail.rb
lib/openapi_client/version.rb

Fixing the regex for `signature_url`
Attempting to suppress the warnings - same as https://github.com/lob/lob-ruby/pull/210/files

GC-1725: attempting to fix url regex

---

CODE_SNIPPETS.md
MIGRATION.md
README.md
__tests__/Integration/UsVerification.spec.rb
docs/UsVerificationsWritable.md
lib/openapi_client/models/us_verifications_writable.rb
lib/openapi_client/version.rb

[GC-1941](https://lobsters.atlassian.net/browse/GC-1941)
Update Lob address from "210 King St." to "2261 Market Street STE 5668, 94114"
Tests are failing [on main](https://github.com/lob/lob-ruby/actions/workflows/run_tests.yml), so these failures are not related to this PR.
[GC-1941]: https://lobsters.atlassian.net/browse/GC-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

GC-1941/updates Lob address
