lob/lob-ruby

lob.gemspec
Should fix the errors we are seeing in the 1.9.3 and jruby builds.
=> fix(prawn): default to prawn 1.3.0 for support for Ruby 1.9.3

lob.gemspec
Allow integrators to use `rest-client` 1.8.0+, which fixes [this vulnerability](https://github.com/rubysec/ruby-advisory-db/blob/master/gems/rest-client/CVE-2015-1820.yml)
`rest-client` is semantically versioned, so it's only the major version you need to pin to.
=> Reduce strictness of rest-client version specification

lib/lob.rb, lob.gemspec
We ran into problems integrating 1.12.0 version of the Lob gem with our Rails 4.1.10 app to the tune of:
```
Bundler could not find compatible versions for gem "rack":
In Gemfile:
rails (~> 4.1.10) ruby depends on
actionpack (= 4.1.10) ruby depends on
rack (~> 1.5.2) ruby
lob (~> 1.12.0) ruby depends on
rack (1.6.0)
```
While upgrading to Rails 4.2 is on our roadmap, we saw that the Lob gem only depends on Rack to use its `build_nested_query` utility, so we took the liberty of excising that method from Rack and adding it to the gem. Happy to reorganize the code if there's a better spot for this method.
=> Break dependency on Rack by implementing build_nested_query

lib/lob.rb
Looks like we just received an error from you guys that could be parsed as JSON but didn't have an `error` key. As a result we saw `NoMethodError: undefined method [] for nil:NilClass`.
It's good practice to protect against all exceptions in an error handling method like `Lob.handle_api_error`.
=> Protect against KeyError in error handling method

.travis.yml, README.md, Rakefile, lib/lob.rb, lib/lob/v1/address.rb, lib/lob/v1/bank_account.rb, lib/lob/v1/check.rb, lib/lob/v1/job.rb, lib/lob/v1/letter.rb, lib/lob/v1/postcard.rb, lib/lob/v1/resource.rb, spec/lob/v1/address_spec.rb, spec/lob/v1/bank_account_spec.rb, spec/lob/v1/check_spec.rb, spec/lob/v1/job_spec.rb, spec/lob/v1/letter_spec.rb, spec/lob/v1/postcard_spec.rb
@robinjoseph08 @elnaz @pon 
Using `city`, `state`, and `zip` instead of `address_city`, etc. was confusing people.
=> Remove address reformatting

lib/lob.rb, lib/lob/errors/lob_error.rb, spec/lob/errors/lob_error_spec.rb
I am writing a lob based app and if I get something wrong I only get this message:
```
Lob::LobError:
Invalid response object:
```
I don't know if that was the intention but I think that it is so much better to respond something like
```
Lob::LobError:
(Status 422) Invalid response object:
{
"errors": [
{
"message": "addrdess_city is not allowed",
"status_code": 422
}
]
}
```
That way if an exception happens it is really easier to understand the cause.
Also the LobError class was overloading some methods from StandardError I don't know if intentionally but we can achieve the same behaviour without overriding anything.
Some tests are failing right now for me in my environment but were failing before the changes and after the results are the same.
=> A small improvement in exception logging

examples/letters.rb
Addresses formated wrong, throwing errors.
@lob/api-engineering-team
=> fix(ruby): address format throwing errors

lib/lob/v1/route.rb, spec/lob/v1/route_spec.rb
Now you can do something like:
```ruby
@lob.routes.list('94107')
```
Fixes #123
=> route list can accept a single ZIP as input

lib/lob.rb
Without this, a `nil` `html_body` will be passed to JSON.parse and raise a `TypeError`. With it, a `JSON::ParserError` will be raised, which will be caught and re-raised as a `LobError` correctly. Allows integrators to handle only `LobError` occurrences and not worry about the more generic `TypeError`.
=> Ensure JSON.parse is never passed nil

spec/lob/v1/route_spec.rb
I added a test that passes multiple zip_codes to the `GET /v1/routes` endpoint. This serves as not only a good test but also as an example for users trying to fetch a combination of routes.
=> add test for routes list endpoint with multiple zip codes

examples/README.md, examples/csv_checks/create_checks.rb, examples/csv_checks/input.csv, examples/csv_letters/create_letters.rb, examples/csv_letters/input.csv, examples/csv_letters/letter_template.html, examples/verify/verify.rb, spec/lob/v1/address_spec.rb
What: Ensure there is a create checks from csv example. Ensure there is a create letters from csv example.
Why: Wrapper tasks
Details:
- Made csv_checks and csv_letters examples
- Edited address spec to be consistent with the syntax of the other tests
=> feat(examples): adds csv checks and csv letters examples

.travis.yml, README.md, spec/lob/v1/address_spec.rb, spec/lob/v1/area_spec.rb, spec/lob/v1/bank_account_spec.rb, spec/lob/v1/check_spec.rb, spec/lob/v1/country_spec.rb, spec/lob/v1/job_spec.rb, spec/lob/v1/letter_spec.rb, spec/lob/v1/object_spec.rb, spec/lob/v1/postcard_spec.rb, spec/lob/v1/route_spec.rb, spec/lob/v1/setting_spec.rb, spec/lob/v1/state_spec.rb, spec/lob_spec.rb, spec/spec_helper.rb
What: No longer need to provide an API key to run tests.
Why: lob-ruby is the only wrapper that requires this. Also, a few tests will fail if certain feature flags  are enabled on the account, so test results vary for different API keys. This eliminates that variability and makes it a bit easier to run tests.
Details:
- Replace environment variable with test API key in `spec_helper.rb`
- Update Readme with new testing instructions.
=> refactor(tests): Remove need to supply API key to run tests

lib/lob.rb, lib/lob/v1/address.rb, lib/lob/v1/area.rb, lib/lob/v1/bank_account.rb, lib/lob/v1/check.rb, lib/lob/v1/client.rb, lib/lob/v1/country.rb, lib/lob/v1/job.rb, lib/lob/v1/letter.rb, lib/lob/v1/object.rb, lib/lob/v1/postcard.rb, lib/lob/v1/resource.rb, lib/lob/v1/route.rb, lib/lob/v1/setting.rb, lib/lob/v1/state.rb, spec/lob_spec.rb
**What**: This refactoring provides a base `Resource` class, from which all other resources (e.g., `Postcard`, `Letters`, etc.) inherit from. It also moves the logic for HTTP requests to the `Resource` class rather than the `Lob` module.
**Why**: The changes involving the `Resource` class remove a lot of duplicated code that was present, specifically the `find`, `create`, `list` and `destroy` methods that were present on (nearly) every resource.
The changes involving the moving of the HTTP requests were made so that the resources behave more like models, responsible for their own communication with the Lob API, not depending on the larger `Lob` module for these communications.
_Details_:
- The old `Resource` class, which was responsible for creating new resources, has been replaced with a …
=> refactor(resource): Refactor classes to inherit from base resource class

.travis.yml
**What & Why**
Remove support for Ruby 1.9.3 as it has not been maintained since February 2014.
Also, add support for Ruby 2.3, as it has been out for nearly a year.
=> feat(ruby-version): Remove support for Ruby 1.9.3 and add support for 2.3

README.md, examples/checks.rb, examples/csv_checks/create_checks.rb, examples/csv_letters/create_letters.rb, examples/csv_postcards/create_postcards.rb, examples/letters.rb, examples/postcards.rb, examples/verify/verify.rb, lib/lob.rb, lib/lob/client.rb, lib/lob/resources/resource_base.rb, spec/lob/resources/address_spec.rb, spec/lob/resources/area_spec.rb, spec/lob/resources/bank_account_spec.rb, spec/lob/resources/check_spec.rb, spec/lob/resources/country_spec.rb, spec/lob/resources/letter_spec.rb, spec/lob/resources/postcard_spec.rb, spec/lob/resources/resource_base_spec.rb, spec/lob/resources/route_spec.rb, spec/lob/resources/state_spec.rb, spec/lob_spec.rb
**What**
Update the configuration of the Lob Ruby wrapper to be more idiomatic.
**Why**
Some of the old ways of configuring the wrapper were a bit strange, and added some unnecessary complexity to the code. This PR simplifies the configuration in the following ways:
- Removes `Lob.load`, `Lob.configure` and `Lob()` syntax.
- Uses `Lob::Client.new(api_key: "api-key")` to set up client.
- Removes ability to specify `protocol` and `api_host` (which defaulted to `https` and `api.lob.com` respectively.
**Details**
Updated all examples and specs to conform to new configuration syntax.
=> feat(config): Update config to be more idiomatic

README.md, examples/README.md, examples/verify/input.csv, examples/verify/input.txt, examples/verify/verify.rb
=> chore(examples): Update examples to use new us_verifications endpoint

.travis.yml
=> feat(versions): Support Ruby 2.3 and 2.4, removes 2.0.0

.travis.yml, spec/lob/resources/us_verifications_spec.rb
=> fix(jruby): Require explicit jruby versions for Travis

examples/checks.rb
It looks like either the comment or the `amount` are incorrect. Comment said $1,000, `amount` == $100.
[[ this PR is being made entirely from github - I didn't clone and run this fork. Let me know if that's not cool. I figured it was ok since a comment change. ]]
=> Fix commented check amount in checks.rb example

lib/lob/resources/bank_account.rb, lib/lob/resources/intl_verifications.rb, lib/lob/resources/resource_base.rb, lib/lob/resources/route.rb, lib/lob/resources/us_verifications.rb, lib/lob/resources/us_zip_lookups.rb, spec/lob/resources/us_verifications_spec.rb
**What**
Adds support for both `query` and `body` to be passed into `us_verifications.verify`.
Previously, the `submit` method only accepted a `parameters` argument, which was either a set of query params (for get and delete methods) or a post body (for post methods). We needed the ability to be able to support both for the `/v1/us_verifications` endpoint, so I made some tweaks:
=> feat(av-case): Support 'case' param for us_verifications

lib/lob/client.rb, lib/lob/resources/group.rb, spec/lob/resources/group_spec.rb
**What:** Adds the `/groups` endpoint functionalities.
**Why:** Rolling this feature out in private beta, and two customers who want to use it use our ruby libraries.
**Details:**
- ~Hoping this will interact properly with the feature flag -- I assume it'll check for permissions on their Lob account after making the call to the regular API? Not sure how our libraries work.~ Confirmed that the feature flag is in place, because builds were failing until I added the feature flag to this account.
- Group members endpoint still yet to come.
JIRA: [ENG-11915](https://lobsters.atlassian.net/browse/ENG-11915)
=> feat(groups): adds the endpoints for suppression groups

lib/lob/resources/resource_base.rb, lob.gemspec, spec/lob/resources/check_spec.rb, spec/lob/resources/letter_spec.rb, spec/lob/resources/postcard_spec.rb
Converts `merge_variables` into JSON
The `rest-client` library was doing some weird data type conversions (e.g. booleans into strings, empty hash into empty string)
=> fix(merge-variables): convert to json

CHANGELOG.md, lib/lob/version.rb
**What**
Updates CHANGELOG.md and bumps client library version identifier from 5.1.2 to 5.2.0
**Why**
Cutting new release with added self mailer support
=> chore: update changelog and bump version to 5.2.0

.github/workflows/update_gem.yml
This PR fixes an error that was encountered when attempting to publish to RubyGems. The version(s) of Ruby need to specified. The previous version of this file didn't do that.
=> specified ruby version in publish action

.github/workflows/run_tests_job.yml, CHANGELOG.md, lib/lob/resources/resource_base.rb, lib/lob/version.rb, lob.gemspec, spec/spec_helper.rb
This makes sure that the lcov.info file is generated by the "rake test" command and sent to coveralls.
=> Fix for coveralls API for GH actions

CHANGELOG.md, lib/lob/resources/bulk_intl_verifications.rb, lib/lob/resources/bulk_us_verifications.rb, lib/lob/version.rb, spec/lob/resources/bulk_intl_verifications_spec.rb, spec/lob/resources/bulk_us_verifications_spec.rb
This PR makes it so that SDK users don't have to do this `lob.bulk_us_verifications.verify(addresses: addresses.to_json)` and can instead do this `lob.bulk_us_verifications.verify(addresses: addresses)` when making calls to the bulk AV resource. 
For more context, look at this issue https://github.com/lob/lob-ruby/issues/201
=> added additional parsing to make sure we can pass hashes into bulk verify methods

__tests__/Api/Require.unit.rb, lib/lob.rb
In reference to [this issue](https://github.com/lob/lob-ruby/issues/207).
=> `require 'lob'` once again loads the library 

__tests__/Api/Address.unit.rb, __tests__/Api/BankAccount.unit.rb, lib/openapi_client/models/bank_account.rb, lib/openapi_client/models/check.rb, lib/openapi_client/models/letter.rb, lib/openapi_client/models/postcard.rb, lib/openapi_client/models/self_mailer.rb, lib/openapi_client/models/thumbnail.rb
In reference to [this issue](https://github.com/lob/lob-ruby/issues/209).
=> Alter regexes and constants in tests to clear up warnings

.github/workflows/run_tests.yml, .github/workflows/update_gem.yml
* [PLAT-2193](https://lobsters.atlassian.net/browse/PLAT-2193)
* `actions/checkout@v3` and `actions/checkout@v2` run Node 12 or 16 and are deprecated, we need them to run Node 20:
See:
https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
and
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
---
[PLAT-2193]: https://lobsters.atlassian.net/browse/PLAT-2193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLAT-2193: update deprecated GitHub Actions
